# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-17 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def fill_status_fild(apps, _):
    fields = [('new', 'Новый'), ('pending', 'Обрабатывается'),
             ('canceled', 'Отменен'), ('delivered', 'Доставлен'),]
    status = apps.get_model('cart', 'Status')
    for key, val in fields:
        st = status.objects.create(slug=key, name=val)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('customer_phone_number', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('total_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Доп. информация')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'verbose_name': 'Заказ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductInBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, verbose_name='Количество')),
                ('price_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Order')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Product')),
            ],
            options={
                'verbose_name_plural': 'товары в заказе',
                'verbose_name': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус заказа')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Статусы',
                'verbose_name': 'Статус',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='new', on_delete=django.db.models.deletion.CASCADE, to='cart.Status', to_field='slug', verbose_name='Статус заказа'),
        ),
        migrations.RunPython(fill_status_fild),
    ]
